config/routes.rb
Rails.application.routes.draw do
  root "events#index"
  get '/sign_in', to: 'users#sign_in'
  post '/sign_in', to: 'users#new_sign_in'
  get '/sign_out', to: 'users#sign_out'
  get 'events/:id/attend', to: 'events#add_attendee', as: 'attend'
  resources :events, only: [:index, :new, :create, :show, :add_attendee]
  resources :users, only: [:new, :create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  self.table_name = 'attendees'

  belongs_to :user
  belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User', foreign_key: :user_id
  has_many :attendances
  has_many :attend, through: :attendances, source: :user

  validates :name, presence: true
  validates :description, presence: true
  validates :date, presence: true
  validates :location, presence: true

  scope :previous_events, -> { where('date < ?', Time.now) }
  scope :upcoming_events, -> { where('date > ?', Time.now) }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events, foreign_key: :creator, class_name: 'Event'
  has_many :attendances
  has_many :attended_events, through: :attendances, source: :event

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  def current_user_now
    User.find(session[:current_user]['id'])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include EventsHelper
  include UsersHelper

  def index
    @previous_events = Event.previous_events
    @upcoming_events = Event.upcoming_events
  end

  def show
    @event = Event.find(params[:id])
    @is_previous_event = Event.previous_events.include? @event
  end

  def new
    if session[:current_user]
      @event = Event.new
    else
      redirect_to sign_in_path
    end
  end

  def create
    user = User.find(session[:current_user]['id'])
    @event = user.events.build(event_params)

    if @event.save
      redirect_to events_path
    else
      render :new
    end
  end

  def add_attendee
    event = Event.find(params[:id])
    user = User.find(session[:current_user]['id'])
    event.attend << user unless event.attend.include? user
    redirect_to event_path(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include UsersHelper

  def new
    if session[:current_user] # Check if there is a current user
      redirect_to events_path
    else
      @user = User.new
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      current_user(@user.id)
      redirect_to @user
    else
      render :new
    end
  end

  def show
    @users = User.all
    if session[:current_user]
      @user = User.find(params[:id])
      @created_events = current_user_now.events
      @previous_events = current_user_now.attended_events.previous_events
      @upcoming_events = current_user_now.attended_events.upcoming_events
    else
      redirect_to sign_in_path
    end
  end

  def new_sign_in
    @user = User.find_by(name: params[:name])
    if @user
      current_user(@user.id)
      redirect_to root_path
    else
      redirect_to sign_in_path, notice: 'Please Sign In'
    end
  end

  def sign_in
    @user = User.find_by(name: params[:name])
    if @user
      @user = User.find_by(name: params[:name])
      p @user
      current_user(@user.id)
      redirect_to events_path
    else
      render :sign_in
    end
  end

  def sign_out
    reset_session
    redirect_to sign_in_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user?
    session[:current_user] = User.find(id)
    session[:current_user]
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def event_params
    params.require(:event).permit(:name, :description, :date, :location, :user)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user(id)
    session[:current_user] = User.find(id)
    session[:current_user]
  end

  def user_params
    params.require(:user).permit(:name)
  end
end

app/views/events/_form.html.erb
<%= simple_form_for(@event) do |f| %>
    <%= f.error_notification%>
    <%= f.input :name %>
    <br>
    <%= f.input :description %>
    <br>
    <%= f.date_field :date %>
    <br><br>
    <%= f.input :location %>
    <%= f.submit class: 'btn btn-primary mt-3 float-end' %>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<section class="container">
<div class="row mt-5 align-items-center">
  <div class="col">
    <h1 class="h3">Events</h1>
  </div>
  <div class="col-2">
    <%= link_to 'Create Event', new_event_path , class: 'text-decoration-none float-end' %>
  </div>
</div>
<h5 class="mt-3 ">Upcoming Events</h5>
<div class="row row-cols-1 row-cols-md-3 g-4">
  <% @upcoming_events.each do |event| %>
  <div class="col">
    <div class="card">
        <div class="card-body">
          <h5 class="card-title"><%= event.name %></h5>
          <h6 class="card-subtitle mb-2 text-muted"><%= event.description %></h6>
          <p class="card-text"><strong>Date:</strong> <%= event.date %> | <strong>Loc.:</strong> <%= event.location %> |<strong> Organizer:</strong> <%= event.creator.name.capitalize %></p>
          <div><%= link_to 'Show', event, class: 'text-decoration-none float-end' %></div>
        </div>
    </div>
  </div>
    <% end %>
</div>
<h5 class="mt-5 ">Previous Events</h5>
<div class="row row-cols-1 row-cols-md-3 g-4">
  <% @previous_events.each do |event| %>
  <div class="col">
    <div class="card">
        <div class="card-body">
          <h5 class="card-title"><%= event.name %></h5>
          <h6 class="card-subtitle mb-2 text-muted"><%= event.description %></h6>
          <p class="card-text"><strong>Date:</strong> <%= event.date %> | <strong>Loc.:</strong> <%= event.location %> |<strong> Organizer:</strong> <%= event.creator.name.capitalize %></p>
          <div><%= link_to 'Show', event, class: 'text-decoration-none float-end' %></div>
        </div>
    </div>
  </div>
    <% end %>
</div>
</section>

app/views/events/new.html.erb
<section class="container">
<div class="row mt-5 align-items-center justify-content-center">
  <div class="col col-md-6">
    <h1 class="h3">New Event</h1>
  </div>
  <div class="col-2">
    <%= link_to 'Back', events_path , class: 'text-decoration-none float-end' %>
  </div>
</div>
    <div class="row justify-content-center">
        <div class="col col-md-8">
            <%= render 'form', event: @event %>
        </div>
    </div>
</section>

app/views/events/show.html.erb
<section class="container mt-5">
 <div class="my-3">
  <%= link_to 'Back', events_path, class: 'text-decoration-none' %>
  <%= link_to 'Attend', attend_path, class: 'btn btn-primary btn-sm float-end' unless @is_previous_event %>

 </div>
 <div class="row">
   <div class="col col-md-6">
    <dl class="row">
      <dt class="col-sm-3">Name:</dt>
      <dd class="col-sm-9"><%= @event.name %> - <%= @event.id%></dd>
    
      <dt class="col-sm-3">Description:</dt>
      <dd class="col-sm-9">
        <p><%= @event.description %></p>
      </dd>
    
      <dt class="col-sm-3">Date:</dt>
      <dd class="col-sm-9"><%= @event.date %></dd>
    
      <dt class="col-sm-3">Location:</dt>
      <dd class="col-sm-9"><%= @event.location %></dd>
      
      <dt class="col-sm-3">Creator:</dt>
      <dd class="col-sm-9"><%= @event.creator.name %></dd>
    </dl>
   </div>
   
   <div class="col col-md-6">
    <strong>Attendees:</strong>
    <ul class="list-group">
      <% @event.attend.each do |a| %>
      <li class="list-group-item"><%= a.name %></li>
      <% end %>
    </ul>
   </div>
 </div>
  
</section>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-light bg-light">
    <div class="container">
        <%= link_to 'Private Events', root_path, class: 'navbar-brand' %>
        <% if session[:current_user] %>
        <div class="d-flex">
        <%= link_to "Hi, #{session[:current_user]['name'].capitalize}", user_path(session[:current_user]['id']), class: 'btn btn-link text-decoration-none' %>
        <%= link_to 'Sign Out', sign_out_path, class: 'btn btn-link text-decoration-none' %>
        </div>
        <% else %>
        <div class="d-flex">
        <%= link_to 'Sign In', sign_in_path, class: 'btn btn-link text-decoration-none' %>
        <%= link_to 'Sign Up', new_user_path, class: 'btn btn-link text-decoration-none' %>
        </div>
        <% end %>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/nav' %>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<section class="container">
    <div class="row justify-content-center">
        <div class="col col-md-5">
            <div class="card border-0 mt-5" style="width: 18rem;">
                <div class="card-body">
                    <h5 class="card-title"><%= title %></h5>
                    <h6 class="card-subtitle mb-2 text-muted"><%= tagline %></h6>
                    <%= simple_form_for(model) do |f| %>
                    <p class="card-text"> <%= f.input :name %></p>
                    <%= f.submit btnlbl, class: 'btn btn-primary mt-3' %>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</section>
                

app/views/users/new.html.erb
<%= render 'form', model: @user, title: "Sign Up", tagline: 'Please signup as new user and create your event!', btnlbl: 'Sign Up' %>

app/views/users/show.html.erb
<section  class="container">
    <div class="row mt-5 align-items-center">
        <div class="col col-md-6">
          <h1 class="h3"><%= @user.name.capitalize %>'s Created Events</h1>
        </div>
        <div class="col-2">
          <%= link_to 'Create Event', new_event_path, class: 'text-decoration-none float-end' %>
        </div>
      </div>
    <div class="row justify-content-start">
        <h6 class="mt-2">Created events</h6>
        <div class="col col-md-8">
            <ol class="list-group list-group-numbered">
                <% @created_events.each do |e| %>
                <li class="list-group-item d-flex justify-content-between align-items-start">
                <div class="ms-2 me-auto">
                    <div class="fw-bold"><%= e.name %></div>
                    <%= e.description %>
                    <%= e.date %>
                    <%= e.location %>
                </div>
                </li>
                <% end %>
            </ol>
        </div>
        <h6 class="mt-2">Previous Events</h6>
        <div class="col col-md-8">
            <ol class="list-group list-group-numbered">
                <% @previous_events.each do |e| %>
                <li class="list-group-item d-flex justify-content-between align-items-start">
                <div class="ms-2 me-auto">
                    <div class="fw-bold"><%= e.name %></div>
                    <%= e.description %>
                    <%= e.date %>
                    <%= e.location %>
                </div>
                </li>
                <% end %>
            </ol>
        </div>
        <h6 class="mt-2">Upcoming Events</h6>
        <div class="col col-md-8">
            <ol class="list-group list-group-numbered">
                <% @upcoming_events.each do |e| %>
                <li class="list-group-item d-flex justify-content-between align-items-start">
                <div class="ms-2 me-auto">
                    <div class="fw-bold"><%= e.name %></div>
                    <%= e.description %>
                    <%= e.date %>
                    <%= e.location %>
                </div>
                </li>
                <% end %>
            </ol>
        </div>
    </div>
</section>

app/views/users/sign_in.html.erb
<section class="container">
    <div class="row justify-content-center">
        <div class="col col-md-5">
            <div class="card border-0 mt-5" style="width: 18rem;">
                <div class="card-body">
                    <h5 class="card-title">Welcome, again!</h5>
                    <h6 class="card-subtitle mb-2 text-muted">Sign In</h6>
                    <%= form_with model: @user do |f|%>
                    <p class="card-text">
                    <%= f.label :name, class:"form-label" %>
                    <%= f.text_field :name, class: "form-control" %>
                    <p class="flash"><%=flash.notice%></p>
                    </p>
                    <%= f.submit 'Sign In', class: 'btn btn-primary mt-3' %>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</section>